// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlQlC00c-DDFMXKaZ8cNQ1ngzhoZqIBaI',
    appId: '1:1079481299182:web:edb3a714c944c1388583ff',
    messagingSenderId: '1079481299182',
    projectId: 'fpractise-35e56',
    authDomain: 'fpractise-35e56.firebaseapp.com',
    storageBucket: 'fpractise-35e56.appspot.com',
    measurementId: 'G-TEM6LMV7D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4uGRDS3KLEVRShh3uqBSHikuVo6CU0iM',
    appId: '1:1079481299182:android:ba0e0af8a8c9b64a8583ff',
    messagingSenderId: '1079481299182',
    projectId: 'fpractise-35e56',
    storageBucket: 'fpractise-35e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaV2wmxsMGjEdIAxgTaa2RtwnmU4Z9ri0',
    appId: '1:1079481299182:ios:1a042bee3c2c7c6f8583ff',
    messagingSenderId: '1079481299182',
    projectId: 'fpractise-35e56',
    storageBucket: 'fpractise-35e56.appspot.com',
    iosBundleId: 'com.example.fFirebase',
  );
}
